sonar.projectKey=cTeacher
sonar.projectName=cTeacher
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=dist/**,node_modules/**,playwright-report/**,coverage/**
sonar.javascript.file.suffixes=.js,.vue
sonar.vue.file.suffixes=.vue
sonar.sourceEncoding=UTF-8
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.js,tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.vue
