<script setup>
/**
 * @file C99LessonsView.vue
 * @description C99 lesson category menu and its individual lesson panels.
 */

import { ref } from "vue";

const activeCategory = ref("");

const categories = [
  { id: "introducing-c", label: "1. Introducing C", buttonClass: "c99-category-button-01 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-01 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-01 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "c-fundamentals", label: "2. C Fundamentals", buttonClass: "c99-category-button-02 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-02 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-02 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "formatted-input-output", label: "3. Formatted Input/Output", buttonClass: "c99-category-button-03 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-03 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-03 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "expressions", label: "4. Expressions", buttonClass: "c99-category-button-04 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-04 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-04 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "selection-statements", label: "5. Selection Statements", buttonClass: "c99-category-button-05 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-05 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-05 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "loops", label: "6. Loops", buttonClass: "c99-category-button-06 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-06 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-06 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "basic-types", label: "7. Basic Types", buttonClass: "c99-category-button-07 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-07 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-07 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "arrays", label: "8. Arrays", buttonClass: "c99-category-button-08 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-08 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-08 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "functions", label: "9. Functions", buttonClass: "c99-category-button-09 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-09 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-09 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "program-organization", label: "10. Program Organization", buttonClass: "c99-category-button-10 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-10 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-10 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "pointers", label: "11. Pointers", buttonClass: "c99-category-button-11 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-11 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-11 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "pointers-and-arrays", label: "12. Pointers and Arrays", buttonClass: "c99-category-button-12 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-12 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-12 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "strings", label: "13. Strings", buttonClass: "c99-category-button-13 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-13 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-13 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "preprocessor", label: "14. Preprocessor", buttonClass: "c99-category-button-14 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-14 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-14 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "writing-large-programs", label: "15. Writing Large Programs", buttonClass: "c99-category-button-15 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-15 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-15 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "structures-unions-enumeration", label: "16. Structures, Unions, and Enumeration", buttonClass: "c99-category-button-16 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-16 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-16 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "advanced-uses-of-pointers", label: "17. Advanced Uses of Pointers", buttonClass: "c99-category-button-17 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-17 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-17 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "declarations", label: "18. Declarations", buttonClass: "c99-category-button-18 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-18 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-18 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "program-design", label: "19. Program Design", buttonClass: "c99-category-button-19 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-19 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-19 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "low-level-programming", label: "20. Low-Level Programming", buttonClass: "c99-category-button-20 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-20 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-20 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "standard-library", label: "21. Standard Library", buttonClass: "c99-category-button-21 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-21 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-21 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "input-output", label: "22. Input/Output", buttonClass: "c99-category-button-22 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-22 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-22 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "library-support-numbers-character-data", label: "23. Library Support for Numbers and Character Data", buttonClass: "c99-category-button-23 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-23 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-23 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "error-handling", label: "24. Error Handling", buttonClass: "c99-category-button-24 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-24 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-24 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "international-features", label: "25. International Features", buttonClass: "c99-category-button-25 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-25 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-25 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "miscellaneous-library-functions", label: "26. Miscellaneous Library Functions", buttonClass: "c99-category-button-26 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-26 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-26 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
  { id: "additional-c99-support-mathematics", label: "27. Additional C99 Support for Mathematics", buttonClass: "c99-category-button-27 box-border flex h-[68px] items-center justify-center rounded-lg border-2 border-cyan-300/60 bg-slate-800/90 px-3 text-center text-sm font-katha-latin font-semibold leading-5 text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", panelClass: "c99-category-panel-27 relative flex h-full min-h-[560px] flex-col rounded-xl border-2 border-cyan-300/60 bg-slate-800/90 p-4 text-slate-100", closeClass: "c99-category-close-27 absolute left-4 top-4 rounded-lg border-2 border-cyan-300/60 bg-slate-900 px-3 py-1 text-xs font-katha-latin font-semibold text-slate-100 transition hover:border-cyan-200 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-cyan-300/70", titleClass: "mt-14 font-katha-latin text-xl font-bold" },
];

function openCategory(categoryId) {
  activeCategory.value = categoryId;
}

function closeCategory() {
  activeCategory.value = "";
}
</script>

<template>
  <section id="c99-lessons-view" class="h-full">
    <div v-if="!activeCategory" id="c99-category-menu" class="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">
      <button
        v-for="category in categories"
        :id="category.buttonClass"
        :key="category.id"
        type="button"
        :class="category.buttonClass"
        @click="openCategory(category.id)"
      >
        <span class="font-katha-latin">{{ category.label }}</span>
      </button>
    </div>

    <div v-else id="c99-category-panel-menu" class="h-full">
      <div v-for="category in categories" :key="`${category.id}-panel`">
        <section
          v-if="activeCategory === category.id"
          :id="category.panelClass"
          :class="category.panelClass"
        >
          <button
            :id="category.closeClass"
            type="button"
            :class="category.closeClass"
            @click="closeCategory"
          >
            Close
          </button>
          <h5 :class="category.titleClass">{{ category.label }}</h5>
        </section>
      </div>
    </div>
  </section>
</template>
